@startuml

actor api
boundary productBatch.routes as routes
control productBatch.controller as controller

activate api
api -> routes: GET /productBatch/search?q=term

activate routes
routes -> controller: searchPb(req, res)
deactivate routes

activate controller
create entity ProductBatch as pb
controller -> pb: ProductBatch.search(term)

database db

activate pb
pb ->> db: SELECT ... WHERE p.Nombre LIKE ? OR p.Descripcion LIKE ?
activate db
db -->> pb: resultados
pb -->> controller: Array de lotes
deactivate pb

controller -->> routes: res.status(200).json(result)
deactivate controller

activate routes
routes -> api: response.status(200)
deactivate routes
deactivate api

@enduml
