@startuml
actor api
boundary qr.routes as routes
control qr.controller as controller
entity user.model as model
database elArca.sql as db

activate api
api -> routes: GET /qr/create

activate routes
routes -> controller: createQR(req, res)
deactivate routes

activate controller

controller ->> model: findByID(req.body.userID)
activate model

model ->> db: execute(\n"SELECT u.*, r.nombreRol AS roleName \n FROM Usuarios u \n INNER JOIN Roles r ON u.idRol = r.idRol \n WHERE u.idUsuario = ? \n LIMIT 1"\n)

activate db

db -->> model: user
deactivate db

model -->> controller: user
deactivate model

alt User is a collaborator
    controller -> api: response.status(403)
else User is a coordinator
    controller -> api: response.status(201)
    deactivate controller
end

deactivate api

@enduml