@startuml
actor api
boundary qr.routes as routes
control qr.controller as controller
entity user.model as model
entity attendance.model as attendanceModel
database elArca.sql as db

activate api
api -> routes: POST /qr/validate

activate routes
routes -> controller: validateQR(req, res)
deactivate routes

activate controller

alt Decrypted read time out of limits
    controller -> api: response.status(406)
else Decrypted read time is inside the limits

    controller ->> model: findByID(decryptedCreator)
    activate model

    model ->> db: execute(\n"SELECT u.*, r.nombreRol AS roleName \n FROM Usuarios u \n INNER JOIN Roles r ON u.idRol = r.idRol \n WHERE u.idUsuario = ? \n LIMIT 1"\n)

    activate db

    db -->> model: user
    deactivate db

    model -->> controller: user
    deactivate model

    alt User is a collaborator
        controller -> api: response.status(406)
    else User is a coordinator
    
        controller ->> model: findByID(req.body.userID)
        activate model
    
        model ->> db: execute(\n"SELECT u.*, r.nombreRol AS roleName \n FROM Usuarios u \n INNER JOIN Roles r ON u.idRol = r.idRol \n WHERE u.idUsuario = ? \n LIMIT 1"\n)
    
        activate db
    
        db -->> model: user
        deactivate db
    
        model -->> controller: user
        deactivate model
    
        controller ->> attendanceModel: addAttendance(userID, userWorkshop, req.body.timestamp)
        
        activate attendanceModel
        
        attendanceModel ->> db: execute(...)
        deactivate attendanceModel
        
        activate db
        
        db -->> attendanceModel: response
        deactivate db
        
        activate attendanceModel
        
        attendanceModel -->> controller: response
        deactivate attendanceModel
        
        controller -> api: response.status(201)
        deactivate controller
    end

    deactivate api

end

@enduml